# Cheat Sheets
https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf  
https://images.datacamp.com/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf

## PANDAS

In [61]:
!pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\shash\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [62]:
!pip install pyarrow


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\shash\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [63]:
# to install pandas run pip install pandas on terminal or !pip install pandas on the code block
from pandas import read_csv

In [64]:
import pandas as pd
df = pd.read_csv("probability.csv")

In [65]:
df

Probability
0      Definitely
1        Probably
2        Not Sure
3    Probably Not
4  Definitely Not
5      something1
6      something2
7      something3

In [66]:
type(df)

pandas.core.frame.DataFrame

In [67]:
#to check the datatype of every column in the dataframe
df.dtypes

Probability    object
dtype: object

In [68]:
# gives the first 4 rows
df.head(n=4)

Probability
0    Definitely
1      Probably
2      Not Sure
3  Probably Not

In [69]:
df.tail(n=3)

Probability
5  something1
6  something2
7  something3

In [70]:
temp = pd.DataFrame({"A":["1","2","3"],"B":[11,12,13],"C":["12-06-12","13-08-23","01-11-18"]})

In [71]:
temp

A   B         C
0  1  11  12-06-12
1  2  12  13-08-23
2  3  13  01-11-18

In [72]:
temp.dtypes

A    object
B     int64
C    object
dtype: object

In [73]:
temp["C"] = pd.to_datetime(temp["C"], format='%y-%m-%d')
temp
temp.dtypes

A            object
B             int64
C    datetime64[ns]
dtype: object

In [74]:
temp["A"] = pd.to_numeric(temp["C"])
temp
temp.dtypes

A             int64
B             int64
C    datetime64[ns]
dtype: object

In [75]:
df.describe

<bound method NDFrame.describe of       Probability
0      Definitely
1        Probably
2        Not Sure
3    Probably Not
4  Definitely Not
5      something1
6      something2
7      something3>

In [76]:
df.info

<bound method DataFrame.info of       Probability
0      Definitely
1        Probably
2        Not Sure
3    Probably Not
4  Definitely Not
5      something1
6      something2
7      something3>

In [77]:
temp.describe

<bound method NDFrame.describe of                      A   B          C
0  1339459200000000000  11 2012-06-12
1  1377216000000000000  12 2013-08-23
2  1006041600000000000  13 2001-11-18>

In [78]:
temp.info

<bound method DataFrame.info of                      A   B          C
0  1339459200000000000  11 2012-06-12
1  1377216000000000000  12 2013-08-23
2  1006041600000000000  13 2001-11-18>

In [79]:
temp["A"].value_counts()

A
1339459200000000000    1
1377216000000000000    1
1006041600000000000    1
Name: count, dtype: int64

In [80]:
temp["A"].value_counts().head(n=1)

A
1339459200000000000    1
Name: count, dtype: int64

In [81]:
#for slicing a dataframe first param is row second param is column
temp1 = temp.iloc[0:2,0:1]
temp1

A
0  1339459200000000000
1  1377216000000000000

In [82]:
temp1.shape

(2, 1)

In [83]:
temp.loc[:,["A","B"]]

A   B
0  1339459200000000000  11
1  1377216000000000000  12
2  1006041600000000000  13

In [84]:
temp[temp["A"]>3]

A   B          C
0  1339459200000000000  11 2012-06-12
1  1377216000000000000  12 2013-08-23
2  1006041600000000000  13 2001-11-18

In [85]:
temp2 = temp[temp["B"].isin([11,13])]
temp2

A   B          C
0  1339459200000000000  11 2012-06-12
2  1006041600000000000  13 2001-11-18

In [86]:
temp2.reset_index(inplace= True, drop=True)
temp2

A   B          C
0  1339459200000000000  11 2012-06-12
1  1006041600000000000  13 2001-11-18

In [87]:
temp


A   B          C
0  1339459200000000000  11 2012-06-12
1  1377216000000000000  12 2013-08-23
2  1006041600000000000  13 2001-11-18

In [88]:
temp.sort_values(by=["A","B"],ascending=[True,False])

A   B          C
2  1006041600000000000  13 2001-11-18
0  1339459200000000000  11 2012-06-12
1  1377216000000000000  12 2013-08-23

In [89]:
temp.groupby("A")["B"].mean()

A
1006041600000000000    13.0
1339459200000000000    11.0
1377216000000000000    12.0
Name: B, dtype: float64

In [90]:
temp.groupby(['A','B'])["B"].agg(["mean","sum"])

mean  sum
A                   B            
1006041600000000000 13  13.0   13
1339459200000000000 11  11.0   11
1377216000000000000 12  12.0   12

In [93]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})


def square(x):
    return x * x


df2 = df1.apply(square)

print(df1)
print(df2)

   A   B
0  1  10
1  2  20
   A    B
0  1  100
1  4  400


## NUMPY

In [94]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\shash\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [97]:
distance = [45,50,35]
speed = [5,10,7]

In [98]:
import numpy as np

In [100]:
dist = np.array(distance)
spd = np.array(speed)
print(dist)
print(spd)
time = dist/spd
print(time)
len(time)

[45 50 35]
[ 5 10  7]
[9. 5. 5.]


3

In [101]:
a = [1,2,3,4]
b = [5,6,7,8]
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [106]:
f = np.array((1,2,3,4,5))
g = np.array((10,20,30,40,50))
print(f)
print(g)
print(f+g)
print(f+5)
print(f**2)
print(g**3)
print(f.dtype)

[1 2 3 4 5]
[10 20 30 40 50]
[11 22 33 44 55]
[ 6  7  8  9 10]
[ 1  4  9 16 25]
[  1000   8000  27000  64000 125000]
int32


In [107]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [108]:
d = np.arange(5,100,2)
print(d)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


In [118]:
data = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,15,16,1,14,3,45,56,7,87))
data2 = data.reshape(2,2,2,3)
data3 = data.reshape(8,3)
print(data)
print(data2)
print(data3)
print(data3.shape)
print(data2.dtype)
even_data = (data%2 == 0)
print(even_data)
print(data[even_data])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 15 16  1 14  3 45 56  7 87]
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [15 16  1]]

  [[14  3 45]
   [56  7 87]]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [15 16  1]
 [14  3 45]
 [56  7 87]]
(8, 3)
int32
[False  True False  True False  True False  True False  True False  True
 False  True False False  True False  True False False  True False False]
[ 2  4  6  8 10 12 14 16 14 56]


In [119]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [122]:
np.zeros((3,5)) *6

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [129]:
np.ones(30)+7

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [125]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [126]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [128]:
np.diag(np.array([1,2,5,4,5,4]))

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 4]])

## MATPLOT LIB AND SEABORN